language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

script:
  - cd /home/travis/gopath/src/github.com/phillikus/goTherm/src/webapp
  - go test -v github.com/phillikus/goTherm/api
  - go test -v github.com/phillikus/goTherm/config
