version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pw
      - POSTGRES_DB=therm_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 
    secrets:
      - psql_pw

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d therm_db"]
      timeout: 10s
      interval: 1m
      retries: 3

secrets:
  psql_pw:
    file: ./local_secrets/psql_pwd.txt

volumes:
  postgres-data: